### ISSUE TITLE
Mods

### ISSUE THREAD

**Issue by xcoress** [aarcangeli/Serious-Sam-Android#7]
Is it even possible in theory to launch modifications on this port? Well, such as dysthymia 9, the bastion of darkness, the mummy (in search of the book Adam Out) and others. Replace textures weapons and all sorts of gory fashion work.

**Comment by aarcangeli** [comment]
I never tried.
I think that it **may** be possible, but it depends from case to case.

In theory it is possible to start any mod that does not have any native files (no dll in bin).
If a mod has some dll, that files must be ported like other dll of the game.
This means that I must have access to the source code of the mod.

Currently the menu is disabled because I want to fix most bugs first.

If you find good mods (with the related source code) I can try

**Comment by xcoress** [comment]
As I understand it, the mummy is a modification curve for SSSE, copying some cards from the first ecounter. Is it possible to get the source code directly from the basement where it was developed ... I will say more, I have not seen a single gro file in the folder.

**Comment by aarcangeli** [comment]
In the last release I have enabled mods.
The problem is that 90% of them will not work.

If you try a mod, can you please report me the result? (both success and failure)

**Comment by xcoress** [comment]
ok

**Comment by xcoress** [comment]
Expected... After a new update, you can run modifications, but when loading a level, it gives an error.
![Screenshot_2019-04-19-14-08-39-886_com github aarcangeli serioussamandroid](https://user-images.githubusercontent.com/47894293/56441455-8c852380-6306-11e9-85b4-d410d621a2fa.png)

**Comment by paoloans** [comment]
How I can put the mods?
Is only a question

**Comment by aarcangeli** [comment]
Exactly like on the computer.
You have to put the mod in the "Mods" directory and then enable it from the menu.

    SeriousSam/
        Mods/
            YourModName/
                BaseBrowseExclude.lst
                BaseBrowseInclude.lst
                ecc...
